db:
  environment:
    MYSQL_ROOT_PASSWORD: ${mysql_root_password}
  image: mysql
  volumes:
  - ${cluster_volume_path}/db:/var/lib/mysql
lb:
  ports:
  - 443:5000
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.ssl.ports: '443'
    io.rancher.scheduler.affinity:host_label: role=${node_label}
    io.rancher.loadbalancer.target.repo-lb: ${fqdn}
  tty: true
  image: rancher/load-balancer-service
  links:
  - web:web
  stdin_open: true
web:
  ports:
  - 5000
  environment:
    DB_USER: root
    DB_PASS: ${mysql_root_password}
  image: derjudge/projectsend
  links:
  - db:mysql