consul:
  image: progrium/consul
  container_name: consul
  restart: always
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  command: -server -bootstrap
swarm-agent:
  image: swarm
  links:
    - consul
  container_name: swarm-agent
  command: join --advertise=<node_ip>:2375 consul://${consul_url}:8500/swarm
swarm-manager:
  image: swarm
  links:
    - consul
  container_name: swarm-manager
  labels:
    - "SERVICE_4000_NAME=swarm-manager"
    - "SERVICE_4000_CHECK_HTTP=http://$SERVICE_IP:4000"
  command: manage -H :4000 --replication --advertise ${advert_host}:4000 consul://${consul_url}:8500/swarm
  ports:
    - "4000:4000"