.catalog:
  name: "YouTransfer"
  version: 0.0.1
  description: YouTransfer file share
  questions:

    - variable: "fqdn"
      type: string
      required: true
      default: 'youtransfer.localdomain'
      label: "FQDN"
      description: "FQDN for virtual host"

    - variable: "node_label"
      type: string
      required: true
      default: 'frontdoor'
      label: "Node Role Label"
      description: "Node role label for loadbalancer"

    - variable: "cluster_volume_path"
      type: string
      required: true
      default: '/mnt/dockervolumes/etherpad'
      label: "Volume Path"
      description: "Cluster volume shared data mount path"

    - variable: "mysql_root_password"
      type: string
      required: true
      default: 'password1'
      label: "MySQL Root Password"
      description: "MySQL administrative user password"

web:
  scale: 3
lb:
  load_balancer_config:
    haproxy_config: {}
  default_cert: load-balancer
  health_check:
    port: 5000
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
