web:
  image: indiehosters/etherpad
  environment:
    - ETHERPAD_ADMIN_PASSWORD=${admin_password}
    - ETHERPAD_ADMIN_USER=${admin_username}
    - ETHERPAD_PORT=80
  ports:
    - 80:80
  volumes:
    - ${cluster_volume_path}/web:/opt/etherpad-lite/var
  links:
    - db:mysql

db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=${mysql_root_password}
  volumes:
    - ${cluster_volume_path}/db:/var/lib/mysql

repo-lb:
  expose:
  - 80:80
  tty: true
  image: rancher/load-balancer-service
  links:
  - web
  stdin_open: true