.catalog:
  name: "Etherpad"
  version: 0.0.1
  description: Etherpad notebook
  questions:

    - variable: "fqdn"
      type: string
      required: true
      default: 'etherpad.localdomain'
      label: "FQDN"
      description: "FQDN for virtual host"

    - variable: "node_label"
      type: string
      required: true
      default: 'frontdoor'
      label: "Node Role Label"
      description: "Node role label for loadbalancer"

    - variable: "cluster_volume_path"
      type: string
      required: true
      default: '/mnt/dockervolumes/etherpad'
      label: "Volume Path"
      description: "Cluster volume shared data mount path"

    - variable: "admin_username"
      type: string
      required: true
      default: 'admin'
      label: "Admin Username"
      description: "Etherpad administrative user name"

    - variable: "admin_password"
      type: string
      required: true
      default: 'password1'
      label: "Admin Password"
      description: "Etherpad administrative user password"

    - variable: "mysql_root_password"
      type: string
      required: true
      default: 'password1'
      label: "MySQL Root Password"
      description: "MySQL administrative user password"

web:
  scale: 3
lb:
  load_balancer_config:
    haproxy_config: {}
  default_cert: load-balancer
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000