artifactory:
  image: mattgruter/artifactory
  ports:
   - "8080:8080"
  volumes:
    - /volumes/artifactory/data:/artifactory/data
    - /volumes/artifactory/artifactory-repositories/logs:/artifactory/logs
    - /volumes/artifactory/artifactory-repositories/backup:/artifactory/backup