lb:
  ports:
  - 443:5000
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.ssl.ports: '443'
    io.rancher.scheduler.affinity:host_label: role=${node_label}
    io.rancher.loadbalancer.target.repo-lb: ${fqdn}
  tty: true
  image: rancher/load-balancer-service
  links:
  - web:web
  stdin_open: true
web:
  ports:
  - 5000
  volume_driver: ${volume_driver}
  image: remie/youtransfer:stable
  volumes:
    - ${cluster_volume_path}/uploads:/opt/youtransfer/uploads
    - ${cluster_volume_path}/config:/opt/youtransfer/config